# @Author: daniel.johnson
# @Date:   2023-02-14 10:49:07
# @Last Modified by:   daniel.johnson
# @Last Modified time: 2023-02-14 10:54:17
name: OWASP ZAP GitHub integration Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testhtml5.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'